name: Update Stock Data

on:
  # schedule:
  #  - cron: "*/15 * * * *"   # každých 15 minut
#  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yfinance pandas
      - run: python scripts/update_intraday.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: "auto: update intraday data"
          add: "data/*.csv"
          push: true
